-- MySQL Script generated by MySQL Workbench
-- Thu Jul 15 17:06:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xpsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xpsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xpsdb` DEFAULT CHARACTER SET utf8 ;
USE `xpsdb` ;

-- -----------------------------------------------------
-- Table `xpsdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpsdb`.`user` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `user_name` VARCHAR(64) NOT NULL COMMENT '用户名',
  `user_pwd` VARCHAR(256) NOT NULL COMMENT '用户密码',
  `phone` VARCHAR(64) NULL,
  `email` VARCHAR(64) NULL COMMENT '邮箱',
  `name` VARCHAR(64) NULL COMMENT '姓名',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `login_last` DATETIME NULL COMMENT '最后一次登录时间',
  `login_total` INT(11) NULL COMMENT '登录次数',
  `creator` VARCHAR(64) NULL COMMENT '创建者',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
