-- MySQL Script generated by MySQL Workbench
-- Mon Aug  9 11:03:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xpsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xpsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xpsdb` DEFAULT CHARACTER SET utf8 ;
USE `xpsdb` ;

-- -----------------------------------------------------
-- Table `xpsdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpsdb`.`user` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `user_name` VARCHAR(64) NOT NULL COMMENT '用户名',
  `user_pwd` VARCHAR(256) NOT NULL COMMENT '用户密码',
  `salt` VARCHAR(256) NULL COMMENT '盐',
  `phone` VARCHAR(64) NULL,
  `email` VARCHAR(64) NULL COMMENT '邮箱',
  `name` VARCHAR(64) NULL COMMENT '姓名',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `login_last` DATETIME NULL COMMENT '最后一次登录时间',
  `login_total` INT(11) NULL COMMENT '登录次数',
  `creator` VARCHAR(64) NULL COMMENT '创建者',
  `OPERATE_CONTENT` VARCHAR(512) NULL COMMENT '操作内容详情',
  `status` INT(2) NULL COMMENT '状态:0 禁用;1 使用',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpsdb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpsdb`.`role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(128) NULL COMMENT '角色名称',
  `role_title` VARCHAR(128) NULL COMMENT '角色标签',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `remark` VARCHAR(256) NULL COMMENT '备注',
  `creator` VARCHAR(64) NULL COMMENT '创建者',
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `xpsdb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpsdb`.`menu` (
  `menu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `menu_name` VARCHAR(64) NOT NULL COMMENT '菜单名称',
  `menu_title` VARCHAR(64) NULL COMMENT '标签',
  `parent_name` VARCHAR(64) NOT NULL COMMENT '父级名称',
  `action` VARCHAR(256) NULL COMMENT '请求地址',
  `order_by` INT(11) NULL COMMENT '排序',
  `status` INT(11) NOT NULL DEFAULT 1 COMMENT '状态:1可用;0:禁用',
  `icon` VARCHAR(64) NULL COMMENT '图标',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `creator` VARCHAR(64) NULL COMMENT '创建者',
  `menu_function` VARCHAR(64) NULL COMMENT '点击菜单触发函数',
  `menu_style` VARCHAR(512) NULL COMMENT '菜单样式名',
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB
COMMENT = '菜单表';


-- -----------------------------------------------------
-- Table `xpsdb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpsdb`.`user_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NOT NULL,
  `menu_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户权限';


-- -----------------------------------------------------
-- Table `xpsdb`.`role_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpsdb`.`role_menu` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NULL,
  `menu_id` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `xpsdb`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `xpsdb`;
INSERT INTO `xpsdb`.`user` (`user_id`, `user_name`, `user_pwd`, `salt`, `phone`, `email`, `name`, `create_time`, `update_time`, `login_last`, `login_total`, `creator`, `OPERATE_CONTENT`, `status`) VALUES (1, 'admin', '4430b8a11a4d62539520bce6de176638', 'Sfv()@)$', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `xpsdb`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `xpsdb`;
INSERT INTO `xpsdb`.`role` (`role_id`, `role_name`, `role_title`, `create_time`, `remark`, `creator`) VALUES (1, 'admin', '管理员', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `xpsdb`.`menu`
-- -----------------------------------------------------
START TRANSACTION;
USE `xpsdb`;
INSERT INTO `xpsdb`.`menu` (`menu_id`, `menu_name`, `menu_title`, `parent_name`, `action`, `order_by`, `status`, `icon`, `create_time`, `creator`, `menu_function`, `menu_style`) VALUES (1, 'mainPage', '系统管理', 'admin', NULL, 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `xpsdb`.`menu` (`menu_id`, `menu_name`, `menu_title`, `parent_name`, `action`, `order_by`, `status`, `icon`, `create_time`, `creator`, `menu_function`, `menu_style`) VALUES (2, 'userManagement', '用户管理', 'mainPage', '/menu/userList', 1, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `xpsdb`.`menu` (`menu_id`, `menu_name`, `menu_title`, `parent_name`, `action`, `order_by`, `status`, `icon`, `create_time`, `creator`, `menu_function`, `menu_style`) VALUES (3, 'menuManagement', '菜单管理', 'mainPage', '/menu/MenuList', 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `xpsdb`.`menu` (`menu_id`, `menu_name`, `menu_title`, `parent_name`, `action`, `order_by`, `status`, `icon`, `create_time`, `creator`, `menu_function`, `menu_style`) VALUES (4, 'roleManagement', '权限管理', 'mainPage', '/menu/roleList', 3, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `xpsdb`.`menu` (`menu_id`, `menu_name`, `menu_title`, `parent_name`, `action`, `order_by`, `status`, `icon`, `create_time`, `creator`, `menu_function`, `menu_style`) VALUES (5, 'jobPage', '任务管理', 'admin', NULL, 2, 1, NULL, NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `xpsdb`.`user_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `xpsdb`;
INSERT INTO `xpsdb`.`user_roles` (`id`, `role_id`, `menu_id`) VALUES (1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `xpsdb`.`role_menu`
-- -----------------------------------------------------
START TRANSACTION;
USE `xpsdb`;
INSERT INTO `xpsdb`.`role_menu` (`id`, `role_id`, `menu_id`) VALUES (1, 1, 1);
INSERT INTO `xpsdb`.`role_menu` (`id`, `role_id`, `menu_id`) VALUES (2, 1, 2);
INSERT INTO `xpsdb`.`role_menu` (`id`, `role_id`, `menu_id`) VALUES (3, 1, 3);
INSERT INTO `xpsdb`.`role_menu` (`id`, `role_id`, `menu_id`) VALUES (4, 1, 4);
INSERT INTO `xpsdb`.`role_menu` (`id`, `role_id`, `menu_id`) VALUES (5, 1, 5);

COMMIT;

