server:
  port: 9090
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://172.17.10.100:33036/rfatest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rfatest
    password: rfatest
    driver-class-name: com.mysql.jdbc.Driver
