server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://172.17.10.159:33036/xpsdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: 55F41AEC312911D8B92BCFBF43B88F60
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:sql/schema-user.sql
      - classpath:sql/update1.0.1/schema-update1.0.1.sql
    data: classpath:sql/update1.0.1/data-update1.0.1.sql
    initialization-mode: never
#mybatis-plus:
#  type-aliases-package: classpath*:com.cao.**.entity
#  mapper-locations: classpath*:/mapper/*/*.xml
